### ISSUE TITLE
Access to Temporary Path Denied

### ISSUE THREAD

**Issue by wjvii** [dotnet/Nerdbank.GitVersioning#447]
I am running into an error during builds that I am not entirely sure how to resolve. This is in Azure DevOps so I am not sure how I would control the permissions on this folder it is trying to use? Any suggestions anyone?

Thank you in advance.

##[error]C:\WINDOWS\ServiceProfiles\NetworkService\.nuget\packages\nerdbank.gitversioning\3.1.68\build\Nerdbank.GitVersioning.targets(151,5): Error MSB4018: The "Nerdbank.GitVersioning.Tasks.AssemblyVersionInfo" task failed unexpectedly.
System.UnauthorizedAccessException: Access to the path 'C:\Users\dtaii\AppData\Local\Temp\vs9482.tmp\Debug' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Nerdbank.GitVersioning.Tasks.AssemblyVersionInfo.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by AArnott** [comment]
Have you used prior versions of NB.GV, and did they give you the same trouble? 3.1.68 is brand new so I wonder if we regressed in this area.

I can't imagine why you wouldn't have access to the `%TEMP%` folder. I wonder if it's that your projects are over-building due to bad P2P references, such that the projects build from multiple processes in prallel, leading to file collisions.

**Comment by wjvii** [comment]
Figured it out. Not sure why it reared its head after years of compiling correctly but there was actually an IntermediateOutputPath parameter in a project file that was causing the issue.
