### ISSUE TITLE
NBGV Fails in GitHub actions PRs

### ISSUE THREAD

**Issue by gfs** [dotnet/Nerdbank.GitVersioning#497]
I am having trouble getting my project (https://github.com/microsoft/OAT) to build in GitHub Actions.  

First I tried `dotnet build` but it failed because NBGV couldn't compute the version from the merge commit hash.

To reduce the number of factors in play I wrote a GitHub Action that just checks out the project and runs the NBGV GitHub Action.

The project configured with GitVersioning (works both locally and in azure pipelines).  

Here's the version.json: https://github.com/microsoft/OAT/blob/main/version.json

The PR with the failing action is here: https://github.com/microsoft/OAT/pull/28

Here's the failing run: https://github.com/microsoft/OAT/runs/985722865?check_suite_focus=true

### Action
```yml
name: NBGV set variables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.3.1
```

### Result
When running it I get this stack trace:

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Unable to get version from commit: 4d82276c99b6b7c4eac31bccade02c5f9d876928
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle)
   at LibGit2Sharp.Core.Proxy.git_commit_tree_id(ObjectHandle obj)
   at LibGit2Sharp.Commit.<>c__DisplayClass11_0.<.ctor>b__0(ObjectHandle obj)
   at LibGit2Sharp.Core.GitObjectLazyGroup.<>c__DisplayClass3_0`1.<Singleton>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at LibGit2Sharp.Core.LazyGroup`1.LazyWrapper`1.LibGit2Sharp.Core.ILazy<TType>.get_Value()
   at LibGit2Sharp.Commit.get_Tree()
   at Nerdbank.GitVersioning.VersionFile.GetVersion(Commit commit, String repoRelativeProjectDirectory)
   at Nerdbank.GitVersioning.GitExtensions.GitWalkTracker.GetVersion(Commit commit)
```

**Comment by AArnott** [comment]
Please see doc at https://github.com/dotnet/nbgv/#checkout-requirements

**Comment by AArnott** [comment]
Reopening to track adding prominent docs to _this_ repo.
