### ISSUE TITLE
Install 3.4 on Fedora 33

### ISSUE THREAD

**Issue by JoKalliauer** [dotnet/Nerdbank.GitVersioning#571]
> Can you please try the latest 3.4 beta? It should totally fix this for you.

_Originally posted by @AArnott in https://github.com/dotnet/Nerdbank.GitVersioning/issues/417#issuecomment-750889893_

How can I install 3.4 ?

I tried
```bash
dotnet tool install -g nbgv
nbgv install
```
as explained at https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/nbgv-cli.md

and got

```bash
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library '/home/jokalliau/.dotnet/tools/.store/nbgv/3.3.37/nbgv/3.3.37/tools/netcoreapp2.1/any/./runtimes/linux-x64/native/libgit2-106a5f2.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libssl.so.1.0.0: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/NativeLibrary.cs:line 44
   at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs:line 401
   at Nerdbank.GitVersioning.GitLoaderContext.LoadUnmanagedDll(String unmanagedDllName) in D:\a\1\s\src\Nerdbank.GitVersioning.Tasks\GitLoaderContext.cs:line 55
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs:line 117
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path)
   at LibGit2Sharp.Core.Proxy.git_libgit2_opts_set_search_path(ConfigurationLevel level, String path)
   at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths)
   at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths)
   at Nerdbank.GitVersioning.Tool.Program.OnInstallCommand(String versionJsonRoot, String version, IReadOnlyList`1 sources) in D:\a\1\s\src\nbgv\Program.cs:line 211
   at Nerdbank.GitVersioning.Tool.Program.MainInner(String[] args) in D:\a\1\s\src\nbgv\Program.cs:line 156
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 399
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs:line 49
   at Nerdbank.GitVersioning.Tool.Program.Main(String[] args) in D:\a\1\s\src\nbgv\Program.cs:line 68
Abgebrochen (Speicherabzug geschrieben)

```

**Comment by AArnott** [comment]
I believe the syntax you're looking for is:

```
dotnet tool install -g nbgv --version 3.4.179-rc
```

**Comment by JoKalliauer** [comment]
I installed nbgv3.4 it with
```bash
dotnet tool update -g nbgv --version 3.4.179-rc
dotnet tool uninstall -g nbgv
dotnet tool install -g nbgv --version 3.4.179-rc
```

However it somehow sill uses 3.3.37 .

I don't know how I tried to install 3.4 . How can I remove all nbgv ?
I tried
```
dotnet tool uninstall -g nbgv
npm remove nerdbank-gitversioning
```

But I still get an error  `.nuget/packages/nerdbank.gitversioning/3.3.37/build/Nerdbank.GitVersioning.Inner.targets` in https://github.com/svg-net/SVG/issues/838 , so I sill have a version 3.3.37 installed.

It seems that in [Readme.md](https://github.com/dotnet/Nerdbank.GitVersioning#installation-and-configuration) does not contain any information how to remove/uninstall nbgv .

**Comment by AArnott** [comment]
@JoKalliauer My guess is you *are* using the latest 3.4 release of `nbgv` after your `dotnet tool` steps. Does `nbgv get-version` work for you?

The error you shared (https://github.com/svg-net/SVG/issues/838) is not from `nbgv` at all, but from the nerdbank.gitversioning nuget package which integrates with your build. You should search your repo for package references to nerdbank.gitversioning and update any version referenced there as well.

**Comment by JoKalliauer** [comment]
```bash
$ nbgv get-version
Version:                      0.0.0.1968
AssemblyVersion:              0.0.0.0
AssemblyInformationalVersion: 0.0.0+b007bb02f4
NuGetPackageVersion:          0.0.0-gb007bb02f4
NpmPackageVersion:            0.0.0-gb007bb02f4
```
