### ISSUE TITLE
FileNotFoundException with managed git implementation

### ISSUE THREAD

**Issue by ssa3512** [dotnet/Nerdbank.GitVersioning#583]
One of our developers is reporting an exception trying to build after latest updates to NBGV. After setting `NBGV_GitEngine` environment variable to `Libgit2` the error went away. He indicated the file mentioned `'C:\Users\dbarrett\source\repos\isolved\.git\objects\pack\pack-00314245d0ca77c6c10a5f87655b8b1e37bbac25.pack'.` does in fact not exist but this doesn't seem to cause any issues with Libgit2.

```
Build started...
1>------ Build started: Project: AOS.Core, Configuration: Debug Any CPU ------
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Error occurred while restoring NuGet packages: The operation failed as details for project AOS.PayrollOffice.WebUI.Foundation could not be loaded.
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.IO.FileNotFoundException: Could not find file 'C:\Users\dbarrett\source\repos\isolved\.git\objects\pack\pack-00314245d0ca77c6c10a5f87655b8b1e37bbac25.pack'.
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: File name: 'C:\Users\dbarrett\source\repos\isolved\.git\objects\pack\pack-00314245d0ca77c6c10a5f87655b8b1e37bbac25.pack'
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitPack.<>c__DisplayClass10_0.<.ctor>b__1()
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitPack..ctor(GetObjectFromRepositoryDelegate getObjectFromRepositoryDelegate, Lazy`1 indexStream, Func`1 packStream, GitPackCache cache)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitPack..ctor(GetObjectFromRepositoryDelegate getObjectFromRepositoryDelegate, String indexPath, String packPath, GitPackCache cache)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitPack..ctor(GitRepository repository, String name)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.LoadPacks()
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at System.Lazy`1.CreateValue()
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at System.Lazy`1.LazyInitValue()
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at System.Lazy`1.get_Value()
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.TryGetObjectBySha(GitObjectId sha, String objectType, Stream& value)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetObjectBySha(GitObjectId sha, String objectType)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetCommit(GitObjectId sha, Boolean readAuthor)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetHeadCommit(Boolean readAuthor)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at MSBuildExtensionTask.ContextAwareTask.Execute()
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\dbarrett\.nuget\packages\nerdbank.gitversioning\3.4.194\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "Nerdbank.GitVersioning.Inner.targets" -- FAILED.
```

**Comment by AArnott** [comment]
@qmfrederik any first ideas?

**Comment by AArnott** [comment]
@ssa3512 any chance you'd be willing to zip up the `.git` directory and share with us for analysis?

**Comment by qmfrederik** [comment]
I'm wondering whether this is related to [Git alternates](https://git-scm.com/docs/gitrepository-layout)?

If it's not possible to share the entire `.git` directory, can you let us know if there's any contents in `objects/info/alternates` or whether `GIT_ALTERNATE_OBJECT_DIRECTORIES` is set?

**Comment by ssa3512** [comment]
Unfortunately I don't think I am going to be able to provide the full `.git` directory. `objects/info/alternates` does not exist and `GIT_ALTERNATE_OBJECT_DIRECTORIES` is not set.

**Comment by qmfrederik** [comment]
@ssa3512 Does, by any chance, your `.git\objects\pack` directory contains an `<name>.idx` file but no matching `<name>.pack` file?

The code first lists all `.idx` files and then opens the matching `.pack` files. I'm wondering whether that assumption fails in your environment.

**Comment by qmfrederik** [comment]
Note - in your case, the question is: do you have happen to have a `C:\Users\dbarrett\source\repos\isolved\.git\objects\pack\pack-00314245d0ca77c6c10a5f87655b8b1e37bbac25.idx` file but no matching `C:\Users\dbarrett\source\repos\isolved\.git\objects\pack\pack-00314245d0ca77c6c10a5f87655b8b1e37bbac25.pack` file?

**Comment by ssa3512** [comment]
> 
> 
> Note - in your case, the question is: do you have happen to have a `C:\Users\dbarrett\source\repos\isolved\.git\objects\pack\pack-00314245d0ca77c6c10a5f87655b8b1e37bbac25.idx` file but no matching `C:\Users\dbarrett\source\repos\isolved\.git\objects\pack\pack-00314245d0ca77c6c10a5f87655b8b1e37bbac25.pack` file?

This is exactly the case - the `idx` file existed but the `pack` did not.

**Comment by AArnott** [comment]
@ssa3512 can you give the fix a try? You can get it from the CI feed here:
https://dev.azure.com/andrewarnott/OSS/_packaging?_a=package&feed=PublicCI&package=Nerdbank.GitVersioning&protocolType=NuGet&version=3.4.200&view=overview

Be sure to select 3.4.200 as the version.

**Comment by AArnott** [comment]
I hope the fix is good. I haven't heard back from @ssa3512 so I'm optimistically closing this.
