### ISSUE TITLE
MissingMethodException for System.Runtime.CompilerServices.Unsafe.ByteOffset, caused by .NET Portability Analyzer

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/Nerdbank.GitVersioning#607]
With Nerdbank.GitVersioning 3.4.203, I get the following error when building a particular .NET Framework C# class library project in the Visual Studio Professional 2017 version 15.9.36 IDE with the  .NET Portability Analyzer 2.7.0.3 extension enabled.

The error does not occur if I disable the  .NET Portability Analyzer extension or run msbuild.exe from the command line. Also, the error does not occur when building another project in the same solution.

```
The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception. ---> System.MissingMethodException: Method not found: 'IntPtr System.Runtime.CompilerServices.Unsafe.ByteOffset(!!0 ByRef, !!0 ByRef)'.
   at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   at System.SpanHelpers.PerTypeValues`1..cctor()
   --- End of inner exception stack trace ---
   at System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   at Nerdbank.GitVersioning.ManagedGit.GitReferenceReader.ReadReference(Stream stream)
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetHeadAsReferenceOrSha()
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetHeadCommit(Boolean readAuthor)
   at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
   at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
   at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
   at MSBuildExtensionTask.ContextAwareTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

The exception is thrown in the devenv.exe process. In WinDbg debugging devenv.exe, `!DumpDomain` shows System Domain, Shared Domain, and Domain 1 (Name: DefaultDomain). 

- System.Runtime.CompilerServices.Unsafe.dll from .NET Portability Analyzer has been loaded to Domain 1. That copy of System.Runtime.CompilerServices.Unsafe.dll has assembly version 4.0.2.0 and AssemblyInformationalVersionAttribute("4.0.0.0"), and lacks the Unsafe.ByteOffset method.
- System.Runtime.CompilerServices.Unsafe.dll from Nerdbank.GitVersioning has not been loaded, as far as I can tell.
- System.Memory.dll from Nerdbank.GitVersioning has been loaded to Domain 1.

I don't currently have a clean repro.

**Comment by KalleOlaviNiemitalo** [comment]
I should:

- Set up a clean repro.
- Find out why the assembly reference was resolved to the older assembly. Do the assembly versions match, or are there binding redirections or resolver event handlers?
- Try changing [ContextAwareTask](https://github.com/dotnet/Nerdbank.GitVersioning/blob/v3.4.203/src/Nerdbank.GitVersioning.Tasks/ContextAwareTask.cs) to derive from [AppDomainIsolatedTask](https://docs.microsoft.com/dotnet/api/microsoft.build.utilities.appdomainisolatedtask?view=netframework-4.7.2).

**Comment by KalleOlaviNiemitalo** [comment]
.NET Portability Analyzer has [AssemblyRedirectResolver](https://github.com/microsoft/dotnet-apiport/blob/8c217e040e115bffbf91cdc9ac9851b5e87e7241/src/ApiPort/ApiPort.VisualStudio/AssemblyRedirectResolver.cs), which seems to completely ignore the requested assembly version. I guess this is a bug in the extension, then.

**Comment by AArnott** [comment]
Thanks for reporting, investigating, and filing the second bug. 
If they don't fix it there, we *might* be able to help by downgrading the dependency versions we use. But I'd rather not go there since I imagine these new APIs provide perf benefits.

**Comment by KalleOlaviNiemitalo** [comment]
I wonder how .NET Framework resolves the `System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, PublicKeyToken=b03f5f7f11d50a3a` reference in System.Memory.dll when .NET Portability Analyzer is not involved. If I understand [How the Runtime Locates Assemblies](https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies) correctly, `System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` does not satisfy the reference by default because the reference is to a strong name and the version does not match exactly.

[AppDomain.AssemblyResolve Event](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve?view=netframework-4.8), which [.NET Portability Analyzer handles](https://github.com/microsoft/dotnet-apiport/blob/d3e847cb89693a3bcdd84e2c68d248e36d37d238/src/ApiPort/ApiPort.VisualStudio/ApiPortVSPackage.cs#L39), is documented as occurring "when the resolution of an assembly fails." Perhaps then, if Nerdbank.GitVersioning upgraded System.Memory.dll to a version that referenced exactly `System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`, .NET Framework would resolve this reference without raising the event and giving .NET Portability Analyzer an opportunity to interfere.

**Comment by AArnott** [comment]
That's a reasonable idea to avoid the problem. But it depends on not just the one assembly, but the transitive closure of assemblies referenced to all agree exactly on the assembly version, which I'd be lucky if I could make that happen *once*, let alone over time as various dependencies get updated. 

What we need is a sound plan in an msbuild task for expressing binding redirects on .NET Framework, or running in a private AssemblyLoadContext on .NET Core. The AppDomainIsolatedTask approach might work for this if it would load a .config file next to the task dll. My https://github.com/AArnott/Nerdbank.MSBuildExtension project provides such isolation in both cases. We could potentially use that here.

**Comment by KalleOlaviNiemitalo** [comment]
> I wonder how .NET Framework resolves the `System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, PublicKeyToken=b03f5f7f11d50a3a` reference in System.Memory.dll when .NET Portability Analyzer is not involved.

I see, [Nerdbank.GitVersioning.Tasks.AssemblyLoader](https://github.com/dotnet/Nerdbank.GitVersioning/blob/8c11e8dee2bfe31652c934dea62b2136de293b63/src/Nerdbank.GitVersioning.Tasks/AssemblyLoader.cs) handles that. [GitHub search for AssemblyResolve](https://github.com/dotnet/Nerdbank.GitVersioning/search?q=AssemblyResolve&type=code) does not find it because the code is only on the `v3.4` branch and not on `master`.

**Comment by KalleOlaviNiemitalo** [comment]
> The AppDomainIsolatedTask approach might work for this if it would load a .config file next to the task dll.

Unfortunately, it ignores such files and just copies the configuration from the parent application domain. <https://github.com/dotnet/msbuild/blob/9802d43bc30b997b75c5efa310a9d379bd56162f/src/Shared/TaskLoader.cs#L88-L96>
