### ISSUE TITLE
Support for amzn.2-x64?

### ISSUE THREAD

**Issue by benmccallum** [dotnet/Nerdbank.GitVersioning#629]
Currently getting a plat not supported exception, so just asking the question.

If it's not supported due to necessary deps or whatever totally understood. Thanks!

**Comment by benmccallum** [comment]
Sorry I did a bit more reading and it seems like upgrading to https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.4.190 might do the trick.

**Comment by benmccallum** [comment]
Interesting, now I'm getting `System.IO.IOException: Not enough storage is available to process this command.`.

Any ideas @AArnott ?

```
[03:45:01][src\AutoGuru.Shared.Cloud\src\AutoGuru.Shared.Cloud.csproj] GetBuildVersion
[03:45:01][GetBuildVersion] MSBuild
[03:45:01][MSBuild] Nerdbank.GitVersioning.Inner.targets: Build target: GetBuildVersion_Properties
[03:45:01][Nerdbank.GitVersioning.Inner.targets] GetBuildVersionCore
[03:45:01][GetBuildVersionCore] Nerdbank.GitVersioning.Tasks.GetBuildVersion
[03:45:01][Nerdbank.GitVersioning.Tasks.GetBuildVersion] C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.4.220\build\Nerdbank.GitVersioning.Inner.targets(17, 5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
System.IO.IOException: Not enough storage is available to process this command.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at Nerdbank.GitVersioning.ManagedGit.GitPack..ctor(GetObjectFromRepositoryDelegate getObjectFromRepositoryDelegate, Lazy`1 indexStream, Func`1 packStream, GitPackCache cache)
   at Nerdbank.GitVersioning.ManagedGit.GitPack..ctor(GetObjectFromRepositoryDelegate getObjectFromRepositoryDelegate, String indexPath, String packPath, GitPackCache cache)
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.LoadPacks()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.TryGetObjectBySha(GitObjectId sha, String objectType, Stream& value)
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.TryGetObjectBySha(GitObjectId sha, String objectType, Stream& value)
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetObjectBySha(GitObjectId sha, String objectType)
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetCommit(GitObjectId sha, Boolean readAuthor)
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetHeadCommit(Boolean readAuthor)
   at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
   at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
   at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
   at MSBuildExtensionTask.ContextAwareTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by benmccallum** [comment]
Dropping down to v3.4.190 exactly seemed to resolve it so it must be a new regression. Let me know if you want me to file it as a new issue @AArnott

**Comment by AArnott** [comment]
Is your Windows agent invoking 32-bit or 64-bit MSBuild? I bet it's 32-bit, which would likely make it a dupe of #584.
