### ISSUE TITLE
Using nbgv get-version results in stacktrace on Jenkins-agent - intermittent

### ISSUE THREAD

**Issue by frankbolero** [dotnet/Nerdbank.GitVersioning#654]
I've been trying to understand why this happens - but I can't.

90%+ of the time - using `nbgv get-version` on my project when building with a dootnet5-agent the end result is an a stack trace. I've been trying to figure out why it works sometimes but I can't find a pattern. It doesn't differ if I install the tool globally or locally. Using the nbgv-tool on my own local machines produces no errors at all and it works as expected.

I use Jenkins 2.242 on Openshift 3.11 (kubernetes) as my CI + build agent.
nbgv --version outputs: `3.4.231+fa7c948811`

Am I missing something?

### version.json
```
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.0-alpha",
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/v\\d+(?:\\.\\d+)?$"
  ],
  "release": {
    "branchName": "release/v{version}"
  },
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  }
}
```

### CLI + Stack trace output
```
./nbgv get-version -v NuGetPackageVersion
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: 'semanticVersion' cannot be an empty string ("") or start with the null character. (Parameter 'semanticVersion')
   at Validation.Requires.NotNullOrEmpty(String value, String parameterName)
   at Nerdbank.GitVersioning.SemanticVersion.TryParse(String semanticVersion, SemanticVersion& version)
   at Nerdbank.GitVersioning.VersionFile.TryReadVersionFile(TextReader versionTextContent)
   at Nerdbank.GitVersioning.VersionFile.GetWorkingCopyVersion(String startingDirectory, String& actualDirectory)
   at Nerdbank.GitVersioning.VersionFile.GetWorkingCopyVersion(String& actualDirectory)
   at Nerdbank.GitVersioning.VersionFile.GetWorkingCopyVersion()
   at Nerdbank.GitVersioning.VersionOracle..ctor(GitContext context, ICloudBuild cloudBuild, Nullable`1 overrideVersionHeightOffset)
   at Nerdbank.GitVersioning.Tool.Program.OnGetVersionCommand(String project, IReadOnlyList`1 metadata, String format, String variable, String commitIsh) in D:\a\1\s\src\nbgv\Program.cs:line 377
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 399
   at System.Delegate.DynamicInvokeImpl(Object[] args) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs:line 89
   at System.Delegate.DynamicInvoke(Object[] args) in /_/src/libraries/System.Private.CoreLib/src/System/Delegate.cs:line 64
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by AArnott** [comment]
Strange.
Does this happen on **CI** builds, **PR** builds, or both? 
Can you repro it if you checkout the same commit used by the jenkins build? In particular for a PR build, the commit the agent checks out will be one you don't have locally, but may be printed in the log somewhere such that you may be able to fetch it explicitly and then `git checkout` to it to see if it happens to repro.

**Comment by frankbolero** [comment]
Yeah I'll try that.
I'll just mention that I have this issue both with an actual production code project and in my super simple test project (which I created for the purpose of trying to understand this issue).

I'll get back with my findings!

**Comment by AArnott** [comment]
It might be interesting if you can script your jenkins agent to dump the version.json file somewhere that you can retrieve after a failure so we can see if it had been corrupted somehow.

**Comment by AArnott** [comment]
Looking more at the code, I see `TryReadVersionFile` reads `version.txt` files -- not `version.json` files. 

I wonder what version.txt file is being read. Is it possible that the jenkins build is producing a new version.txt file that nbgv then ends up reading? nbgv will look for any and *all* version.txt files at the directory given (or current directory) and above all the way up to the root. Could a version.txt file be created somewhere new that nb.gv is then picking up?

The exception suggests that the first line of this version.txt file is empty.

**Comment by frankbolero** [comment]
I think I just had a similar idea... The thing is I'm a bit new to this tool AND I'm also new to Jenkins.

Just now I thought that _maybe_ there's something going on when I'm writing my file. A file called version.txt. This is done via './nbgv get-version -v NuGetPackageVersion > version.txt'...

**Comment by frankbolero** [comment]
Yeah, that's it. Since I wrote the output to version.txt it dumped a stacktrace and exited. :)

Thank you so much for your input @AArnott !

**Comment by AArnott** [comment]
You're welcome.
