### ISSUE TITLE
SetCloudBuildVariables `System.ObjectDisposedException: Cannot access a closed Stream`

### ISSUE THREAD

**Issue by xperiandri** [dotnet/Nerdbank.GitVersioning#690]
```
2021-11-16T21:24:54.6882780Z ##[section]Starting: Build .NET Core project Mobile/SuperCharge.Mobile/SuperCharge.Mobile.fsproj
2021-11-16T21:24:54.6896320Z ==============================================================================
2021-11-16T21:24:54.6896660Z Task         : .NET Core
2021-11-16T21:24:54.6897300Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
2021-11-16T21:24:54.6897660Z Version      : 2.187.0
2021-11-16T21:24:54.6897900Z Author       : Microsoft Corporation
2021-11-16T21:24:54.6898260Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
2021-11-16T21:24:54.6898690Z ==============================================================================
2021-11-16T21:24:55.1381140Z Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
2021-11-16T21:24:55.1452830Z [command]/Users/runner/hostedtoolcache/dotnet/dotnet build /Users/runner/work/1/s/Mobile/SuperCharge.Mobile/SuperCharge.Mobile.fsproj -dl:CentralLogger,"/Users/runner/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.187.0/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"*ForwardingLogger,"/Users/runner/work/_tasks/DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b/2.187.0/dotnet-build-helpers/Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" -c Release
2021-11-16T21:24:56.0850420Z 
2021-11-16T21:24:56.0868230Z Welcome to .NET 6.0!
2021-11-16T21:24:56.0869870Z ---------------------
2021-11-16T21:24:56.0870310Z SDK Version: 6.0.100
2021-11-16T21:24:56.0870460Z 
2021-11-16T21:24:56.0870690Z Telemetry
2021-11-16T21:24:56.0871290Z ---------
2021-11-16T21:24:56.0872540Z The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
2021-11-16T21:24:56.0873180Z 
2021-11-16T21:24:56.0873950Z Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
2021-11-16T21:24:56.0874230Z 
2021-11-16T21:24:56.0875000Z ----------------
2021-11-16T21:24:56.0875370Z Installed an ASP.NET Core HTTPS development certificate.
2021-11-16T21:24:56.0876220Z To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
2021-11-16T21:24:56.0877200Z Learn about HTTPS: https://aka.ms/dotnet-https
2021-11-16T21:24:56.0877880Z ----------------
2021-11-16T21:24:56.0878650Z Write your first app: https://aka.ms/dotnet-hello-world
2021-11-16T21:24:56.0879460Z Find out what's new: https://aka.ms/dotnet-whats-new
2021-11-16T21:24:56.0880400Z Explore documentation: https://aka.ms/dotnet-docs
2021-11-16T21:24:56.0880880Z Report issues and find source on GitHub: https://github.com/dotnet/core
2021-11-16T21:24:56.0881790Z Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
2021-11-16T21:24:56.0882720Z --------------------------------------------------------------------------------------
2021-11-16T21:24:56.8877960Z Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
2021-11-16T21:24:56.8890050Z Copyright (C) Microsoft Corporation. All rights reserved.
2021-11-16T21:24:56.8902430Z 
2021-11-16T21:24:58.0029480Z   Determining projects to restore...
2021-11-16T21:25:02.3259140Z   Restored /Users/runner/work/1/s/Shared/FSharp/SuperCharge.FSharp.fsproj (in 2.52 sec).
2021-11-16T21:25:02.3273480Z   Restored /Users/runner/work/1/s/Shared/Domain/SuperCharge.Domain.fsproj (in 2.52 sec).
2021-11-16T21:25:02.3275130Z   Restored /Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj (in 2.52 sec).
2021-11-16T21:25:02.8902820Z   Restored /Users/runner/work/1/s/Mobile/SuperCharge.Mobile/SuperCharge.Mobile.fsproj (in 536 ms).
2021-11-16T21:25:03.7097900Z   Generated files:
2021-11-16T21:25:09.7951050Z   SuperCharge.FSharp -> /Users/runner/work/1/s/Shared/FSharp/bin/iPhoneSimulator/Release/netstandard2.0/SuperCharge.FSharp.dll
2021-11-16T21:25:09.9845610Z ##[error]/Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): Error MSB4018: The "Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables" task failed unexpectedly.
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at Nerdbank.GitVersioning.CloudBuildServices.VisualStudioTeamServices.<>c__DisplayClass13_0.<SetCloudBuildVariable>b__0()
   at Nerdbank.GitVersioning.Utilities.FileOperationWithRetry(Action operation)
   at Nerdbank.GitVersioning.CloudBuildServices.VisualStudioTeamServices.SetCloudBuildVariable(String name, String value, TextWriter stdout, TextWriter stderr)
   at Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
2021-11-16T21:25:09.9853220Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables" task failed unexpectedly. [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9854540Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018: System.ObjectDisposedException: Cannot access a closed Stream. [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9855660Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9856790Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9857900Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at System.IO.StreamWriter.WriteLine(String value) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9858980Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at System.IO.TextWriter.SyncTextWriter.WriteLine(String value) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9860200Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Nerdbank.GitVersioning.CloudBuildServices.VisualStudioTeamServices.<>c__DisplayClass13_0.<SetCloudBuildVariable>b__0() [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9861430Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Nerdbank.GitVersioning.Utilities.FileOperationWithRetry(Action operation) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9862810Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Nerdbank.GitVersioning.CloudBuildServices.VisualStudioTeamServices.SetCloudBuildVariable(String name, String value, TextWriter stdout, TextWriter stderr) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9864620Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables.Execute() [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9866060Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:09.9867510Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.2986520Z   SuperCharge.Domain -> /Users/runner/work/1/s/Shared/Domain/bin/iPhoneSimulator/Release/netstandard2.0/SuperCharge.Domain.dll
2021-11-16T21:25:10.3232030Z 
2021-11-16T21:25:10.3241290Z Build FAILED.
2021-11-16T21:25:10.3342240Z 
2021-11-16T21:25:10.3458660Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables" task failed unexpectedly. [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3472930Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018: System.ObjectDisposedException: Cannot access a closed Stream. [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3475360Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3477390Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3478590Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at System.IO.StreamWriter.WriteLine(String value) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3479710Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at System.IO.TextWriter.SyncTextWriter.WriteLine(String value) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3480920Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Nerdbank.GitVersioning.CloudBuildServices.VisualStudioTeamServices.<>c__DisplayClass13_0.<SetCloudBuildVariable>b__0() [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3482200Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Nerdbank.GitVersioning.Utilities.FileOperationWithRetry(Action operation) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3483490Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Nerdbank.GitVersioning.CloudBuildServices.VisualStudioTeamServices.SetCloudBuildVariable(String name, String value, TextWriter stdout, TextWriter stderr) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3484770Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables.Execute() [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3486740Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3488180Z /Users/runner/.nuget/packages/nerdbank.gitversioning/3.4.244/build/Nerdbank.GitVersioning.targets(115,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/runner/work/1/s/Shared/Elmish/SuperCharge.Elmish.fsproj]
2021-11-16T21:25:10.3489150Z     0 Warning(s)
2021-11-16T21:25:10.3489400Z     1 Error(s)
2021-11-16T21:25:10.3489520Z 
2021-11-16T21:25:10.3489790Z Time Elapsed 00:00:12.97
2021-11-16T21:25:10.3516090Z ##[error]Error: The process '/Users/runner/hostedtoolcache/dotnet/dotnet' failed with exit code 1
2021-11-16T21:25:10.3525620Z ##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
2021-11-16T21:25:10.3531460Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
2021-11-16T21:25:10.3535040Z ##[error]Dotnet command failed with non-zero exit code on the following projects : /Users/runner/work/1/s/Mobile/SuperCharge.Mobile/SuperCharge.Mobile.fsproj
2021-11-16T21:25:10.3618480Z ##[section]Async Command Start: Update Build Number
2021-11-16T21:25:10.3619020Z Update build number to 1.0.0-dev+75d1208294 for build 1160
2021-11-16T21:25:10.3619330Z ##[section]Async Command End: Update Build Number
2021-11-16T21:25:10.3621290Z ##[section]Finishing: Build .NET Core project Mobile/SuperCharge.Mobile/SuperCharge.Mobile.fsproj
```

**Comment by xperiandri** [comment]
This happens on macOS and Ubuntu but not on Windows hosted agents

**Comment by AArnott** [comment]
NB.GV is just writing to stdout here. This looks like a bug that should be taken up with Azure Pipelines. Have you tried the "Report a Bug" command to report it yet?
![image](https://user-images.githubusercontent.com/3548/142227771-0d5e5692-87b6-4add-87c6-c09967921901.png)

As a workaround, you could disable setting the cloud build variables. In your version.json file you can disable with:

```json
{
  "cloudBuild": {
    "setVersionVariables": false
  }
}

**Comment by AArnott** [comment]
Closing due to no response.
